name: I18n Translation Check and Update

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master

jobs:
  translate:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-genai pyyaml markdown

      # Step 4: Run i18n check and translation script
      - name: Check and translate i18n content
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python .github/scripts/i18n_translator.py
      
      # Step 5: Commit and push changes if any
      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add i18n/
          if git diff --staged --quiet; then
            echo "No translation changes to commit"
          else
            git commit -m "Update i18n translations [skip ci]"
            git push
          fi
