name: Update Download Version

on:
  repository_dispatch:
    types: [update-download-version]
  workflow_dispatch:
    inputs:
      version:
        description: '要更新的版本号（需要包含前面的v）'
        required: true
        type: string

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      latest_sha: ${{ steps.get_latest_sha.outputs.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整的历史记录，以便进行文件差异比较

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML # Assuming PyYAML might be needed for markdown parsing, or other libraries if the script becomes more complex

      - name: Run Update Download Version Script
        id: run_script
        env:
          NEW_VERSION: ${{ github.event.client_payload.version || github.event.inputs.version }}
        run: python .github/scripts/update_download_version.py

      - name: Commit and push if changes
        id: commit_push
        if: success()
        run: |
          git diff --quiet cherrystudio/download.md || \
          (
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add cherrystudio/download.md
            git commit -m "Auto: Update download links to ${{ github.event.client_payload.version || github.event.inputs.version }}"
            git push
          )
          echo "No changes to commit or changes committed."
      - name: Get latest SHA after push
        id: get_latest_sha
        if: success()
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  dispatch-translation-workflow:
    needs: update-version
    if: success() # 确保 update-version job 成功
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.update-version.outputs.latest_sha }} # 检出 update-version job 推送后的最新提交
          fetch-depth: 0 # 获取完整的历史记录，以便进行文件差异比较
      - name: Get current and previous commit SHAs
        id: get_shas
        run: |
          AFTER_SHA=$(git rev-parse HEAD)
          if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
            BEFORE_SHA=$(git rev-parse HEAD^)
          else
            BEFORE_SHA=$AFTER_SHA # 如果没有父提交，则 before_sha 等于 after_sha
          fi
          echo "before_sha=$BEFORE_SHA" >> $GITHUB_OUTPUT
          echo "after_sha=$AFTER_SHA" >> $GITHUB_OUTPUT
      - name: Dispatch translate-docs workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }} # 需要一个具有 repo 权限的 token
          repository: CherryHQ/cherry-studio-docs # 触发自身仓库的 workflow
          event-type: trigger-translation # 触发 translate-docs.yml 的 trigger-translation 事件
          client-payload: '{"before_sha": "${{ steps.get_shas.outputs.before_sha }}", "after_sha": "${{ steps.get_shas.outputs.after_sha }}"}'
